version: '3'

services:  
  # FAIR Data Point server    
  fdp:
    image: fairdata/fairdatapoint:1.12.0
    volumes:
      - fdp-server:/fdp/
    depends_on:
      - mongo
    networks:
      - default
      - bootstrap_graphdb_net    
        
  # FAIR Data Point client	
  fdp_client:
    image: fairdata/fairdatapoint-client:1.12.0
    hostname: fdp_client
    environment:
      FDP_HOST: fdp
#      FDP_HOST: fdp
    volumes:
      - fdp-client-scss:/src/scss/custom/
      - fdp-client-assets:/usr/share/nginx/html/
    depends_on:
      - fdp
    ports:
      - 8080:80
    networks:
      - default
      
  # Mongo for FDP server    
  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - default
      
# Define networks here
networks:
  bootstrap_graphdb_net:
    external: true

volumes:
  mongo-data:
    external: true
  mongo-init:
    external: true
  fdp-client-assets:
    external: true
  fdp-client-scss:
    external: true
  fdp-server:
    external: true

